### ISSUE TITLE
Unhandled edge case for Products being removed from API

### ISSUE THREAD

**Issue by borislavml** [tomaswalander/azure-and-devops-tools#1]
Hi there Tomas,hope I'm not intruding
I've stumbled upon an edge case when publishing and updating existing API Products, we do not delete a Product that has been removed from the products array, which is a problem and could be dangerous.
Here's a visual example:
![api-config](https://user-images.githubusercontent.com/7393707/215085014-1689dade-f76f-4e94-a080-5e3cdd28d21e.png)

Not that good with JS/TS and tooling, but I did wrote a quick "fix", which unfortunately I haven't found a way to test in the real world, but here's a proposal:

After calling `api.beginCreateOrUpdateAndWait` and before calling `productApi.createOrUpdate`: 
 # Get existing Products for the API, and if a product is not part of the passed products (being added), remove the API from the Product 
 
```
    for await (let page of client.apiProduct.listByApis(resourceGroupName, apiManagementName, name).byPage()) {
      for(const pr of page) {
        if(pr.name != null && !products.includes(pr.name)) {
            await client.productApi.delete(resourceGroupName, apiManagementName, pr.name, name);
        }       
      }
    }
```
 
 I can do a PR when I have 100% tested and working so you can publish a new package version. 
 Nothing urgent really, but something we need to be fixed in the long term.

**Comment by tomaswalander** [comment]
Thanks for raising this issue!

Yes, It's true that the tool will not delete product assignments when removed from the list. Similarly, it will not:
1. delete remove operations (e.g., an endpoint) from an API
2. delete an entire API

This was actually by design; IMO, automating deletions is a bit dangerous, but also not straight forward. At least deleting entire API:s - it would have to look at git history or something. 

Deleting product assignments and operations can of course be done but to some extent I think it's cleaner to only have this tool create/assign things and rather leave deletions as manual clean-up tasks.

IMO, it would make sense to keep the current behaviour of never removing anything.
BUT, it needs to be clearly stated in docs that it is the intended behaviour. 

Thoughts?

**Comment by borislavml** [comment]
Sorry for the late response!
 
 Giving it a second thought I DO agree with all you've said above. The "_edge case_" is more of a project specific, and  the package shouldn't be concerned with it. We'll update our docs to clearly state this behavior, as this now passes silently and "_unnoticed_".Sometimes one might really want to perform product un-assignment, but if so it should be done explicitly!
 I'll be communicating all of this with the rest of the teams and DevOps, and if at some point we find ourselves in need of this functionality, I hope you won't mind us forking the repo and releasing a "_different_" npm package for our use.

 Thanks for the response and have a great week!

**Comment by tomaswalander** [comment]
I've been thinking this over a bit more and perhaps it would make sense to have the option to automate deletions.

WDYT about: 

1. By default the tool will NOT delete anything - it will create new endpoints, update existing and assign new products.
2. Adding a flag that changes the behaviour of the tool to also remove superfluous operations and/or product assignments.

E.g.,
```
  --remove-unknown-assignments        If used the tool will remove Product Assignments from each API if not specified in the api-config.json. (default: false)
  --remove-unknown-operations         If used the tool will remove Operations from each API if not specified in the api-config.json. (default: false)
```

If you would want this behaviour you could just use the flags.

**Comment by borislavml** [comment]
I was also thinking of adding the deletion behavior via flags explicitly, but rather on the `api-config.json` level so it's more flexible and can be controlled per API. Something along the lines of  :  
```
  {
    "displayName": "My API,
    "operations": [
      {
        "id": "my-operation-1"
      }
    ],
    "operations_remove_unknown": false
    "products": [
      "my product"
    ],
    "products_remove_unknown": true
  }
```   
` operations_remove_unknown` and `products_remove_unknown` of course being non-mandatory and default to `false`. And maybe also have the option of flagging on **cli level**(as you've described) and applying it for all APIs in the config. But this will maybe make it convoluted which flag has higher precedence, both for usage and implementation 🤔  I wouldn't really mind any of the two as long as they are there to use 😄

**Comment by tomaswalander** [comment]
@borislavml terribly sorry about the delay! I've been very busy at work. 

**Firstly,** I've decided to split this in two parts: 

1. [Remove unknown product assignments - PR](https://github.com/tomaswalander/azure-and-devops-tools/pull/2)
2. [Remove unknown API operations - Issue](https://github.com/tomaswalander/azure-and-devops-tools/issues/3).

The reason for this separation is that removing a product assignment is a lot more trivial; and this issue originally was specifically only about the first (1) part. I have opened a separate issue for the second one to track progress there.

**Secondly**, the more I think about it; the more I've realised that the "options" (`products_remove_unknown`) which discussed above are not necessary. I think it's reasonable to let the script remove unknown product assignments; since this script is not intended to be used together with manually manipulating APIs and/or product assignments. Therefore, I've implemented this as the default behaviour. 

**Finally - ask for help!**

I currently do not have access to any Api Management I could use to test this. Would you be able to help me? I've written instructions for how to test in the [PR](https://github.com/tomaswalander/azure-and-devops-tools/pull/2). As it's only in PR-state you need to start by doing something like;

1. Ensure you have the right Node version (16.15.1) installed and install yarn using `npm install -g yarn`.
2. clone the repository and check out the right branch (feature/remove-unknown-api-product-assignments-from-apim). 
3. run `yarn` to install dependencies
4. Step into the `clis/ado-cli` folder

From here you should be able to run the script using `yarn dev <normal command and options stuff here>`.
OR you can run `yarn build` and then run it using `yarn ado-cli  <normal command and options stuff here>` if you prefer. Both options run the script directly from the repository and does not install anything globally on your laptop; so you have to remain in the CI folder.

**Comment by borislavml** [comment]
Hey @tomaswalander. Thanks for looking into the issue. I've been also quite busy at work, but I'll DO try to find some time the following week to properly test the PR branch with all the Azure infra setup needed. Will write back when I can confirm for sure it's working as expected!

**Comment by tomaswalander** [comment]
@borislavml new version `0.1.0` available. You can test it, e.g., through npx: 

```
npx @twalander/ado-cli@0.1.0 --help
```

IIRC, you need to modify your pipelines to use the new version explicitly :)

**Comment by borislavml** [comment]
All testing performer, 

> @borislavml new version `0.1.0` available. You can test it, e.g., through npx:
> 
> ```
> npx @twalander/ado-cli@0.1.0 --help
> ```
> 
> IIRC, you need to modify your pipelines to use the new version explicitly :)

Yep we DO need to do that :). Tested via npx with the new version - all's working as expected. Many thanks for the support 🙏

**Comment by tomaswalander** [comment]
Great news! Thanks for opening the issue and helping with testing!
